const { GoogleGenAI } = require("@google/genai");
const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});
const puppeteer = require("puppeteer");
const path = require('path');
const fs = require('fs');

async function getExecutablePath() {
    // 1. Prioritize an explicit ENV variable if it exists
    if (process.env.PUPPETEER_EXECUTABLE_PATH) return process.env.PUPPETEER_EXECUTABLE_PATH;

    // 2. Locate the .cache folder inside the backend directory
    // On Render, process.cwd() is /opt/render/project/src/backend
    const cachePath = path.join(process.cwd(), '.cache', 'puppeteer', 'chrome');
    
    if (!fs.existsSync(cachePath)) {
        console.error("Puppeteer cache not found at:", cachePath);
        return null;
    }

    // 3. Automatically find the chrome binary inside the versioned folders
    const versions = fs.readdirSync(cachePath);
    if (versions.length > 0) {
        // Path: .cache/puppeteer/chrome/linux-<version>/chrome-linux64/chrome
        return path.join(cachePath, versions[0], 'chrome-linux64', 'chrome');
    }

    return null;
}

async function generatePdfFromHtml(htmlContent) {
  let browser;
  try {
    const launchOptions = {
      headless: true,
      timeout: 60000,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--disable-extensions", // Extra stability
      ],
    };

    browser = await puppeteer.launch(launchOptions);
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "domcontentloaded" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      margin: {
        top: "10mm",
        bottom: "10mm",
        left: "10mm",
        right: "10mm",
      },
    });

    return pdfBuffer;
  } finally {
    if (browser) {
      try {
        await browser.close();
      } catch (closeError) {
        const proc = browser.process();
        if (proc && !proc.killed) {
          proc.kill("SIGKILL");
        }
      }
    }
  }
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  const prompt = `Generate resume for a candidate with the following details:
    Resume: ${resume}
    Self Description: ${selfDescription}
    Job Description: ${jobDescription}

    the response should be a string of  JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
    The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
    The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
    you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
    The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
    The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
`;
  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
    },
  });

  const jsonContent = JSON.parse(response.text);

  const pdfBuffer = await generatePdfFromHtml(jsonContent.html);
  return pdfBuffer;
}

module.exports = generateResumePdf;
